spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.18.127:8848
        username: nacos
        password: nacos

  datasource:
    username: root
    password: 365373011
    url: jdbc:mysql://192.168.18.127:3306/lyra_qq_bot_app
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 192.168.18.127
      port: 6379
      password: 365373011
logging:
  level:
    com.lyra.qqbot.processor: debug

random-pony-image-api:
  url: http://192.168.18.127:7979
  group: /randomImage/pony
  randomLyraImg: /randomLyraImg
  randomBackgroundPonyImage: /randomBackgroundPonyImage
  randomTSImage: /RandomTSImage
  randomRDImage: /RandomRDImage
  randomRRImage: /RandomRRImage
  randomSnowdropImage: /RandomSnowdropImage
  randomNyxImage: /RandomNyxImage
  randomPinkiePieImage: /RandomPinkiePieImage
  randomFlutterShyPieImage: /RandomFlutterShyPieImage
  randomAppleJackPieImage: /RandomAppleJackPieImage
  randomLunaImage: /RandomLunaImage
  getRandomPonyImageToTag: /GetRandomPonyImageToTag

  weather:
    public-key: U0E730BB18
    secret-key: zp79vxlbj2ojus2y
